# fly.toml file generated for pf2-db-uploader on 2022-11-23T23:41:52-08:00

app = "pf2-db-uploader"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]


[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]